In [11]:
import pandas as pd
from pathlib import Path

In [12]:
# Define the path to the CSV file (use absolute path)
Data = Path("RESOURCES/Data Team Performance Task_Raw Dataset (1).xlsx - 2017-18 STAAR GRADE 3 ELA (2).csv")

# Read the CSV file into a pandas DataFrame
Data_df = pd.read_csv(Data)

In [13]:
# Define the path to the CSV file (use absolute path)
Data2 = Path("RESOURCES/Data Team Performance Task_Raw Dataset (1).xlsx - 2018-19 STAAR GRADE 3 ELA (2).csv")

# Read the CSV file into a pandas DataFrame
Data_df2 = pd.read_csv(Data2)

In [14]:
header_mapping2 = {
    'CDB03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CNC03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'CD003ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'CDL03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CNS03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'CDH03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CNM03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'CD403ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CNC03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'CD003ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'CDL03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CNS03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'CDH03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CNM03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'CD403ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CNC03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'CD003ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'CDL03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CNS03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'CDH03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CNM03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'CD403ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CNC03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'CD003ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'CDL03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CNS03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'CDH03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CNM03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'CD403ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1S19R': 'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CNC03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'CD003ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'CDL03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CNS03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'CDH03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CNM03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'CD403ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1319R': 'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CNC03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'CD003ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'CDL03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CNS03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'CDH03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CNM03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'CD403ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1219R': 'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate'}

In [15]:
# Rename columns using the header mapping dictionary
Data_df2 = Data_df2.rename(columns=header_mapping2)

In [16]:
Data_df2.to_csv("HEADER-2018-19 STAAR GRADE 3 ELA (2).csv")

In [35]:
Data_df2.replace([-1, '.'], pd.NA, inplace=True)

In [36]:
for col in Data_df2.columns:
    if col != 'CAMPUS':
        Data_df2[col] = Data_df2[col].astype('Int64')

In [37]:
Data_df2

,CAMPUS,"Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate",...,"Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate"
0,'001902001,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,'001902041,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,'001902103,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,9,20,91,90,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,'001903001,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,'001903002,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8833,'254901101,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8834,'254901104,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8835,'254901106,17,<NA>,0,<NA>,50,<NA>,<NA>,<NA>,<NA>,...,8,25,38,69,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8836,'254902001,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8837,'254902101,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,20,20,80,100,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [20]:
Data_df

,CAMPUS,CD203ARE1217R,CD203ARE1218R,CD203ARE1317R,CD203ARE1318R,CD203ARE1S17R,CD203ARE1S18R,CD303ARE1217R,CD303ARE1218R,CD303ARE1317R,...,CDS03ARE1317R,CDS03ARE1318R,CDS03ARE1S17R,CDS03ARE1S18R,CDW03ARE1217R,CDW03ARE1218R,CDW03ARE1317R,CDW03ARE1318R,CDW03ARE1S17R,CDW03ARE1S18R
0,'001902001,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
1,'001902041,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2,'001902103,-1,-1,-1,-1,-1,-1,.,-1,.,...,-1,-1,-1,-1,41,59,26,28,67,87
3,'001903001,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
4,'001903041,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,'254901101,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
8755,'254901104,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
8756,'254901106,.,.,.,.,.,.,.,.,.,...,-1,-1,-1,-1,-1,.,-1,.,-1,.
8757,'254902001,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
8758,'254902101,.,.,.,.,.,.,.,.,.,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [21]:
header_mapping= {
    'CDB03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CDL03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CDH03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CD403ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1S17R': 'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CDL03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CDH03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CD403ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1317R': 'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CDL03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CDH03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CD403ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1217R': 'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CDL03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CDH03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CD403ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CDL03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CDH03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CD403ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1318R': 'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'CDB03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'CDA03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CDL03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CDH03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CD403ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1218R': 'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate'
}

In [22]:
# Rename columns using the header mapping dictionary
Data_df = Data_df.rename(columns=header_mapping)

In [23]:
Data_df

,CAMPUS,"Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate",...,"Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate"
0,'001902001,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
1,'001902041,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2,'001902103,-1,-1,-1,-1,-1,-1,.,-1,.,...,-1,-1,-1,-1,41,59,26,28,67,87
3,'001903001,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
4,'001903041,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,'254901101,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
8755,'254901104,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
8756,'254901106,.,.,.,.,.,.,.,.,.,...,-1,-1,-1,-1,-1,.,-1,.,-1,.
8757,'254902001,.,.,.,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
8758,'254902101,.,.,.,.,.,.,.,.,.,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [24]:
# Identify columns with potential non-numeric values
for col in Data_df.columns:
    if col != 'CAMPUS':
        non_numeric_values = Data_df[~Data_df[col].apply(lambda x: str(x).isdigit())][col]
        if not non_numeric_values.empty:
            print(f"Non-numeric values in column {col}:")
            print(non_numeric_values)

Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate, Length: 8646, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate, Length: 8657, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate, Length: 8646, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate, Length: 8657, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate, Length: 8646, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate, Length: 8657, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate, Length: 8273, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate, Length: 8330, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate, Length: 8273, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate, Length: 8330, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate, Length: 8273, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate, Length: 8330, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate:
0       .
1       .
3       .
4       .
5       .
       ..
8752    .
8753    .
8754    .
8755    .
8757    .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate, Length: 4643, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate:
0       .
1       .
3       .
4       .
5       .
       ..
8752    .
8753    .
8754    .
8755    .
8757    .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate, Length: 4727, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate:
0       .
1       .
3       .
4       .
5       .
       ..
8752    .
8753    .
8754    .
8755    .
8757    .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate, Length: 4643, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate:
0       .
1       .
3       .
4       .
5       .
       ..
8752    .
8753    .
8754    .
8755    .
8757    .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate, Length: 4727, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate:
0       .
1       .
3       .
4       .
5       .
       ..
8752    .
8753    .
8754    .
8755    .
8757    .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate, Length: 4643, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate:
0       .
1       .
3       .
4       .
5       .
       ..
8752    .
8753    .
8754    .
8755    .
8757    .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate, Length: 4727, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756    -1
8757     .
8758     .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate, Length: 8170, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate, Length: 8308, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756    -1
8757     .
8758     .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate, Length: 8170, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate, Length: 8308, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756    -1
8757     .
8758     .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate, Length: 8170, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8754     .
8755     .
8756     .
8757     .
8758     .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate, Length: 8308, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate, Length: 5450, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate, Length: 5705, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate, Length: 5450, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate, Length: 5705, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate, Length: 5450, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate, Length: 5705, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate, Length: 5100, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate:
0        .
1        .
3        .
4        .
5        .
        ..
8753     .
8754     .
8755     .
8756    -1
8757     .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate, Length: 5368, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate, Length: 5100, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate:
0        .
1        .
3        .
4        .
5        .
        ..
8753     .
8754     .
8755     .
8756    -1
8757     .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate, Length: 5368, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate, Length: 5100, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate:
0        .
1        .
3        .
4        .
5        .
        ..
8753     .
8754     .
8755     .
8756    -1
8757     .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate, Length: 5368, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate, Length: 5605, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate, Length: 5940, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate, Length: 5605, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate, Length: 5940, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate, Length: 5605, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate:
0        .
1        .
2       -1
3        .
4        .
        ..
8752     .
8753     .
8754     .
8755     .
8757     .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate, Length: 5940, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate, Length: 8759, dtype: object
Non-numeric values in column Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate:
0       .
1       .
2       .
3       .
4       .
       ..
8754    .
8755    .
8756    .
8757    .
8758    .
Name: Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate, Length: 8759, dtype: object

In [25]:
# Convert columns to integer with handling for non-numeric values
for col in Data_df.columns:
    if col != 'CAMPUS':
        # Replace non-numeric values with NaN
        Data_df[col] = pd.to_numeric(Data_df[col], errors='coerce')
        # Fill NaN values with a specific value if needed, e.g., 0
        Data_df[col] = Data_df[col].fillna(0)
        # Convert to integer type
        Data_df[col] = Data_df[col].astype('Int64')  # 'Int64' allows for NaNs, if you filled NaNs with 0, 'int' would work too

In [26]:
Data_df

,CAMPUS,"Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate",...,"Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate"
0,'001902001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,'001902041,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,'001902103,-1,-1,-1,-1,-1,-1,0,-1,0,...,-1,-1,-1,-1,41,59,26,28,67,87
3,'001903001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,'001903041,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8754,'254901101,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8755,'254901104,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8756,'254901106,0,0,0,0,0,0,0,0,0,...,-1,-1,-1,-1,-1,0,-1,0,-1,0
8757,'254902001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8758,'254902101,0,0,0,0,0,0,0,0,0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [27]:
D

NameError: name 'D' is not defined

In [ ]:
for col in Data_df.columns:
    if col != 'CAMPUS':
        Data_df[col] = Data_df[col].astype('Int64')

ValueError: invalid literal for int() with base 10: '.'

In [ ]:
Data_df.replace([-1, '.'], pd.NA, inplace=True)

In [ ]:
Data_df.to_csv("2017-18 STAAR GRADE 3 ELA.csv")

### DASH APP

### TAB 1

In [ ]:
from jupyter_dash import JupyterDash
from dash import dcc, html
from dash.dependencies import Output, Input
from dash.exceptions import PreventUpdate

import plotly.express as px
import pandas as pd
import plotly.io as pio
pio.renderers.default = 'notebook'

import pandas as pd
from pathlib import Path

In [ ]:
# Define the path to the CSV file (use absolute path)
Data3 = Path("Overview Data\Data Team Performance Task_Raw Dataset.xlsx - 2018-19 CAMPUS (2).csv")

# Read the CSV file into a pandas DataFrame
Data_df3 = pd.read_csv(Data3)

In [ ]:
Data_df3

,CAMPUS,CAD_GAP,CAD_MATH,CAD_POST,CAD_PROGRESS,CAD_READ,CAD_SCIE,CAD_SOCI,CAMPNAME,CFLALTED,CFLCHART,CNTYNAME,COUNTY,C_RATING,DISTNAME,DISTRICT,GRDSPAN,GRDTYPE,REGION
0,'001902001,1.0,1.0,1.0,1.0,1.0,1.0,1.0,CAYUGA H S,N,N,ANDERSON,'001,A,CAYUGA ISD,'001902,'09 - 12,S,'07
1,'001902041,0.0,0.0,1.0,0.0,1.0,0.0,0.0,CAYUGA MIDDLE,N,N,ANDERSON,'001,B,CAYUGA ISD,'001902,'06 - 08,M,'07
2,'001902103,1.0,1.0,1.0,1.0,0.0,0.0,NaN,CAYUGA EL,N,N,ANDERSON,'001,A,CAYUGA ISD,'001902,'PK - 05,E,'07
3,'001903001,0.0,1.0,0.0,1.0,1.0,1.0,1.0,ELKHART H S,N,N,ANDERSON,'001,B,ELKHART ISD,'001903,'09 - 12,S,'07
4,'001903002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ELKHART DAEP,N,N,ANDERSON,'001,Not Rated,ELKHART ISD,'001903,'08 - 10,S,'07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8833,'254901101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DR TOMAS RIVERA EL,N,N,ZAVALA,'254,F,CRYSTAL CITY ISD,'254901,'EE - 01,E,'20
8834,'254901104,0.0,0.0,0.0,0.0,0.0,0.0,NaN,BENITO JUAREZ MIDDLE,N,N,ZAVALA,'254,C,CRYSTAL CITY ISD,'254901,'05 - 06,M,'20
8835,'254901106,0.0,0.0,0.0,0.0,0.0,NaN,NaN,ZAVALA EL,N,N,ZAVALA,'254,F,CRYSTAL CITY ISD,'254901,'02 - 04,E,'20
8836,'254902001,0.0,1.0,1.0,0.0,0.0,0.0,0.0,LA PRYOR H S,N,N,ZAVALA,'254,B,LA PRYOR ISD,'254902,'07 - 12,S,'20
8837,'254902101,0.0,0.0,0.0,0.0,0.0,0.0,NaN,LA PRYOR EL,N,N,ZAVALA,'254,C,LA PRYOR ISD,'254902,'PK - 06,E,'20

In [ ]:
Data_df3['GRDTYPE'].unique()

array(['S', 'M', 'E', 'B'], dtype=object)

In [ ]:
#Groupby District
#Pull count district Rating
dist_ratings = Data_df3.groupby(['DISTNAME', 'C_RATING']).size().unstack(fill_value=0)
#only show Elementary campuses
el_campus_data = Data_df3[Data_df3['GRDTYPE'] == 'E']
#Only Show Middle School Campuses
middle_campus_data = Data_df3[Data_df3['GRDTYPE'] == 'M']
#ony show High School campuses
hs_campus_data = Data_df3[Data_df3['GRDTYPE'] == 'S']
#ony show Charter campuses
charter_campus_data = Data_df3[Data_df3['GRDTYPE'] == 'B']

In [ ]:
import dash_bootstrap_components as dbc

# Create the Dash app
app = JupyterDash(__name__, external_stylesheets=[dbc.themes.SUPERHERO])

# Front end layout
app.layout = dbc.Container([
    html.H1("School District Dashboard"),

    dcc.Tabs([
        dcc.Tab(label='Academic Achievement & Ratings', children=[
            dbc.Container([
                dbc.Row([
                    dbc.Col(dcc.Dropdown(
                        id="SD",
                        options=[{'label': 'All DISTRICTS', 'value': 'All'}] +
                                [{'label': district, 'value': district} for district in Data_df3['DISTNAME'].unique()],
                        style={'color': 'black'},
                        value='All'  # Default value
                    ), width=6),

                    dbc.Col(dcc.RadioItems(
                        id='SchoolType',
                        options=[
                            {'label': 'Elementary', 'value': 'E'},
                            {'label': 'Middle', 'value': 'M'},
                            {'label': 'High', 'value': 'S'},
                            {'label': 'Charter', 'value': 'B'},
                            {'label': 'All', 'value': 'All'}
                        ],
                        value='All'  # Default value
                    ), width=6),
                ], className='mb-4'),

                dbc.Row([
                    dbc.Col([
                        html.H3("Academic Achievement in Mathematics", style={'textAlign': 'center'}),
                        dcc.Graph(id='Mathg', style={'width': '400px', 'height': '400px'}),
                        html.P(id='Math', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Academic Achievement in English Language Arts/Reading", style={'textAlign': 'center'}),
                        dcc.Graph(id='rlag', style={'width': '400px', 'height': '400px'}),
                        html.P(id='rla', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Academic Achievement in Science", style={'textAlign': 'center'}),
                        html.Br(),
                        html.Div(style={'height': '0.5em'}),
                        dcc.Graph(id='scienceg', style={'width': '400px', 'height': '400px'}),
                        html.P(id='science', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),
                ]),

                dbc.Row([
                    dbc.Col([
                        html.H3("Academic Achievement in Social Studies", style={'textAlign': 'center'}),
                        dcc.Graph(id='ssg', style={'width': '400px', 'height': '400px'}),
                        html.P(id='ss', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Top 25 Percent: Comparative Academic Growth", style={'textAlign': 'center'}),
                        dcc.Graph(id='cgg', style={'width': '400px', 'height': '400px'}),
                        html.P(id='cg', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Top 25 Percent: Comparative Closing the Gaps", style={'textAlign': 'center'}),
                        dcc.Graph(id='cg2g', style={'width': '400px', 'height': '400px'}),
                        html.P(id='cg2', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),
                ]),

                html.H2("SCHOOL RATINGS", style={'textAlign': 'center', 'marginTop': '40px'}),
                dcc.Graph(id='Graph1', style={'height': '600px'}),
            ], fluid=True)
        ]),

        dcc.Tab(label='Different Dashboard', children=[
            html.Div([
                html.H2("Student Performance", style={'textAlign': 'center'}),
                # Add content for the second tab here
            ])
        ])
    ])
], fluid=True)

# Backend callback
@app.callback(
    [
        Output("Mathg", "figure"),
        Output("rlag", "figure"),
        Output("scienceg", "figure"),
        Output("ssg", "figure"),
        Output("cgg", "figure"),
        Output("cg2g", "figure")
    ],
    [Input("SD", "value"),
     Input("SchoolType", "value")]
)
def update_cards(selected_district, selected_school_type):
    # Filter DataFrame based on selected district
    if selected_district == 'All':
        filtered_df = Data_df3
    else:
        filtered_df = Data_df3[Data_df3['DISTNAME'] == selected_district]

    # Further filter by school type
    if selected_school_type != 'All':
        filtered_df = filtered_df[filtered_df['GRDTYPE'] == selected_school_type]

    # Calculate the total number of possible points (rows in filtered_df)
    total_possible_points = filtered_df.shape[0]

    # Check if there are no rows to avoid division by zero
    if total_possible_points == 0:
        return (px.pie(names=["N/A"], values=[1], hole=0.5),) * 6
    
    # Calculate counts
    Ma = filtered_df['CAD_MATH'].sum()
    Rla = filtered_df['CAD_READ'].sum()
    sc = filtered_df['CAD_SCIE'].sum()
    ss = filtered_df['CAD_SOCI'].sum()
    cad = filtered_df['CAD_PROGRESS'].sum()
    pro = filtered_df['CAD_GAP'].sum()
    
    # Create pie charts with percentage representation
    def create_pie_chart(count, total):
        return px.pie(
            names=['Earned', 'Not Earned'],
            values=[count, total - count],
            title=f"{count} out of {total} possible points",
            hole=0.5,
            labels={'Earned': 'Earned', 'Not Earned': 'Not Earned'},
            color_discrete_sequence=['red', 'green']
        ).update_layout(
            title_text=f"{count/total*100:.1f}%",
            title_x=0.5,
            title_y=0.85
        )

    # Generate pie charts
    pie_math = create_pie_chart(Ma, total_possible_points)
    pie_rla = create_pie_chart(Rla, total_possible_points)
    pie_science = create_pie_chart(sc, total_possible_points)
    pie_ss = create_pie_chart(ss, total_possible_points)
    pie_cg = create_pie_chart(cad, total_possible_points)
    pie_cg2 = create_pie_chart(pro, total_possible_points)
    
    return (pie_math, pie_rla, pie_science, pie_ss, pie_cg, pie_cg2)

# Callback to update the graphs
@app.callback(
    Output("Graph1", "figure"),
    [Input("SD", "value"),
     Input("SchoolType", "value")]
)
def update_graphs(selected_district, selected_school_type):
    # Filter DataFrame based on selected district
    if selected_district == 'All':
        filtered_df = Data_df3
    else:
        filtered_df = Data_df3[Data_df3['DISTNAME'] == selected_district]

    # Further filter by school type
    if selected_school_type != 'All':
        filtered_df = filtered_df[filtered_df['GRDTYPE'] == selected_school_type]
    
    # Group by 'C_RATING' and count occurrences
    rating_counts = filtered_df.groupby('C_RATING').size().reset_index(name='Count')
    
    # Define color mapping for each rating
    color_map = {
        'A': 'green',
        'B': 'blue',
        'C': 'orange',
        'D': 'purple',
        'Data Integrity Issues': 'pink',
        'F': 'red',
        'Not Rated': 'black'
    }
    
    # Order the categories
    rating_order = ['A', 'B', 'C', 'D', 'F', 'Data Integrity Issues', 'Not Rated']
    
    # Create bar chart
    fig1 = px.bar(
        rating_counts,
        x='C_RATING',
        y='Count',
        title='School Rating Count',
        color='C_RATING',
        color_discrete_map=color_map,
        category_orders={'C_RATING': rating_order}
    )
    
    # Update the legend title
    fig1.update_layout(
        legend_title_text='School Ratings',
        title='',
        xaxis_title='School Rating',
        yaxis_title=''
    )
    
    return fig1

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8059)

c:\Users\HP\anaconda3\Lib\site-packages\dash\dash.py:550: UserWarning:

JupyterDash is deprecated, use Dash instead.
See https://dash.plotly.com/dash-in-jupyter for more details.

Dash app running on http://127.0.0.1:8059/

#### TAB 2

In [39]:
merge_df=pd.merge(Data_df3, Data_df2, on='CAMPUS')

In [40]:
merge_df

,CAMPUS,CAD_GAP,CAD_MATH,CAD_POST,CAD_PROGRESS,CAD_READ,CAD_SCIE,CAD_SOCI,CAMPNAME,CFLALTED,...,"Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate"
0,'001902001,1.0,1.0,1.0,1.0,1.0,1.0,1.0,CAYUGA H S,N,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,'001902041,0.0,0.0,1.0,0.0,1.0,0.0,0.0,CAYUGA MIDDLE,N,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,'001902103,1.0,1.0,1.0,1.0,0.0,0.0,NaN,CAYUGA EL,N,...,9,20,91,90,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,'001903001,0.0,1.0,0.0,1.0,1.0,1.0,1.0,ELKHART H S,N,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,'001903002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ELKHART DAEP,N,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8833,'254901101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DR TOMAS RIVERA EL,N,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8834,'254901104,0.0,0.0,0.0,0.0,0.0,0.0,NaN,BENITO JUAREZ MIDDLE,N,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8835,'254901106,0.0,0.0,0.0,0.0,0.0,NaN,NaN,ZAVALA EL,N,...,8,25,38,69,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8836,'254902001,0.0,1.0,1.0,0.0,0.0,0.0,0.0,LA PRYOR H S,N,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8837,'254902101,0.0,0.0,0.0,0.0,0.0,0.0,NaN,LA PRYOR EL,N,...,20,20,80,100,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [ ]:
colums = [
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Continuous Enrollee, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Current-&-Monitored-Y1toY4-EL, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
]

In [ ]:
merge_df.columns

Index(['CAMPUS', 'CAD_GAP', 'CAD_MATH', 'CAD_POST', 'CAD_PROGRESS', 'CAD_READ',
       'CAD_SCIE', 'CAD_SOCI', 'CAMPNAME', 'CFLALTED',
       ...
       'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
       'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
       'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
       'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
       'Campus 2017 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
       'Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
       'Campus 2017 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
       'Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
       'Campus 2017 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate',
       'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate'],
      dtype='object', length=103)

In [ ]:
merge_df

,CAMPUS,CAD_GAP,CAD_MATH,CAD_POST,CAD_PROGRESS,CAD_READ,CAD_SCIE,CAD_SOCI,CAMPNAME,CFLALTED,...,"Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Mobile, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate","Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Former Special Ed, STAAR Reading/ELA Rate"
0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,NaN,0.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,NaN,1.0,1.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,...,9,20,91,90,-1,-1,-1,-1,-1,-1
3,NaN,0.0,1.0,0.0,1.0,1.0,1.0,1.0,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8834,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8835,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,...,8,25,38,69,-1,<NA>,-1,<NA>,-1,<NA>
8836,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8837,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,20,20,80,100,<NA>,-1,<NA>,-1,<NA>,-1

In [41]:
import dash_bootstrap_components as dbc

# Create the Dash app
app = JupyterDash(__name__, external_stylesheets=[dbc.themes.SUPERHERO])

# Front end layout
app.layout = dbc.Container([
    html.H1("School District Dashboard"),

    dcc.Tabs([
        dcc.Tab(label='Student Performance', children=[
            dbc.Container([
                dbc.Row([
                    dbc.Col(dcc.Dropdown(
                        id="SD",
                        options=[{'label': 'All DISTRICTS', 'value': 'All'}] +
                                [{'label': district, 'value': district} for district in merge_df['DISTNAME'].unique()],
                        style={'color': 'black'},
                        value='All'  # Default value
                    ), width=6),

                    dbc.Col(dcc.RadioItems(
                        id='SchoolType',
                        options=[
                            {'label': 'Elementary', 'value': 'E'},
                            {'label': 'Middle', 'value': 'M'},
                            {'label': 'High', 'value': 'S'},
                            {'label': 'Charter', 'value': 'B'},
                            {'label': 'All', 'value': 'All'}
                        ],
                        value='All'  # Default value
                    ), width=6),
                ], className='mb-4'),

                dbc.Row([
                    dbc.Col([
                        html.H3("Female Vs Male-Approaches", style={'textAlign': 'center'}),
                        dcc.Graph(id='FMAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='FMA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Female Vs Male-Meets", style={'textAlign': 'center'}),
                        dcc.Graph(id='FMMG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='FMM', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Female Vs Male-Masters", style={'textAlign': 'center'}),
                        html.Br(),
                        html.Div(style={'height': '0.5em'}),
                        dcc.Graph(id='FMMAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='FMMA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),
                ]),
                html.Br(),
                html.Br(),
                dbc.Row([
                    dbc.Col([
                        html.H3("Performance by Race-Approaches", style={'textAlign': 'center'}),
                        dcc.Graph(id='RAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='RA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Performance by Race-Meets", style={'textAlign': 'center'}),
                        dcc.Graph(id='RAMG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='RAM', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Performance by Race-Masters", style={'textAlign': 'center'}),
                        html.Br(),
                        html.Div(style={'height': '0.5em'}),
                        dcc.Graph(id='RMAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='RMA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),
                ])
            ])
        ])
    ])
], fluid=True)

# Backend callback
@app.callback(
    [
        Output("FMAG", "figure"),
        Output("FMMG", "figure"),
        Output("FMMAG", "figure"),
        Output("RAG", "figure"),
        Output("RAMG", "figure"),
        Output("RMAG", "figure")
    ],
    [Input("SD", "value"),
     Input("SchoolType", "value")]
)
def update_cards(selected_district, selected_school_type):
    # Filter DataFrame based on selected district
    if selected_district == 'All':
        filtered_df = merge_df
    else:
        filtered_df = merge_df[merge_df['DISTNAME'] == selected_district]

    # Further filter by school type
    if selected_school_type != 'All':
        filtered_df = filtered_df[filtered_df['GRDTYPE'] == selected_school_type]

    # Define columns for each graph
    fmag_cols = [
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate'
    ]
    fmmg_cols = [
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate'
    ]
    fmmag_cols = [
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate'
    ]
    rag_cols = [
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate'
    ]
    ramg_cols = [
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Meets Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate'
    ]
    raag_cols = [
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
        'Campus 2019 Domain 1A: Masters Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate'
    ]

    # Calculate averages
    def calculate_averages(cols):
        return filtered_df[cols].mean().to_dict()

    # Generate bar graphs
    def generate_bar_graph(averages, title):
        return px.bar(
            x=list(averages.keys()),
            y=list(averages.values()),
            labels={'x': 'Category', 'y': 'Average Rate'},
            title=title
        )

    fmag_averages = calculate_averages(fmag_cols)
    fmmg_averages = calculate_averages(fmmg_cols)
    fmmag_averages = calculate_averages(fmmag_cols)
    rag_averages = calculate_averages(rag_cols)
    ramg_averages = calculate_averages(ramg_cols)
    raag_averages = calculate_averages(raag_cols)

    return (
        generate_bar_graph(fmag_averages, 'Female Vs Male Approaches'),
        generate_bar_graph(fmmg_averages, 'Female Vs Male Meets'),
        generate_bar_graph(fmmag_averages, 'Female Vs Male Masters'),
        generate_bar_graph(rag_averages, 'Performance by Race Approaches'),
        generate_bar_graph(ramg_averages, 'Performance by Race Meets'),
        generate_bar_graph(raag_averages, 'Performance by Race Masters')
    )

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8060)

c:\Users\HP\anaconda3\Lib\site-packages\dash\dash.py:550: UserWarning:

JupyterDash is deprecated, use Dash instead.
See https://dash.plotly.com/dash-in-jupyter for more details.

Dash app running on http://127.0.0.1:8060/

In [ ]:
import dash_bootstrap_components as dbc

# Create the Dash app
app = JupyterDash(__name__, external_stylesheets=[dbc.themes.SUPERHERO])

# Front end layout
app.layout = dbc.Container([
    html.H1("School District Dashboard"),

    dcc.Tabs([
        dcc.Tab(label='Student Performance', children=[
            dbc.Container([
                dbc.Row([
                    dbc.Col(dcc.Dropdown(
                        id="SD",
                        options=[{'label': 'All DISTRICTS', 'value': 'All'}] +
                                [{'label': district, 'value': district} for district in Data_df3['DISTNAME'].unique()],
                        style={'color': 'black'},
                        value='All'  # Default value
                    ), width=6),

                    dbc.Col(dcc.RadioItems(
                        id='SchoolType',
                        options=[
                            {'label': 'Elementary', 'value': 'E'},
                            {'label': 'Middle', 'value': 'M'},
                            {'label': 'High', 'value': 'S'},
                            {'label': 'Charter', 'value': 'B'},
                            {'label': 'All', 'value': 'All'}
                        ],
                        value='All'  # Default value
                    ), width=6),
                ], className='mb-4'),

                dbc.Row([
                    dbc.Col([
                        html.H3("Female Vs Male-Approaches", style={'textAlign': 'center'}),
                        dcc.Graph(id='FMAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='FMA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Female Vs Male-Meets", style={'textAlign': 'center'}),
                        dcc.Graph(id='FMMG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='FMM', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Female Vs Male-Masters", style={'textAlign': 'center'}),
                        html.Br(),
                        html.Div(style={'height': '0.5em'}),
                        dcc.Graph(id='FMMAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='FMMA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),
                ]),
                html.Br(),
                html.Br(),
                dbc.Row([
                    dbc.Col([
                        html.H3("Performace by Race-Approaches", style={'textAlign': 'center'}),
                        dcc.Graph(id='RAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='RA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Performace by Race-Meets", style={'textAlign': 'center'}),
                        dcc.Graph(id='RAMG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='RAM', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),

                    dbc.Col([
                        html.H3("Performace by Race-Masters", style={'textAlign': 'center'}),
                        html.Br(),
                        html.Div(style={'height': '0.5em'}),
                        dcc.Graph(id='RMAG', style={'width': '400px', 'height': '400px'}),
                        html.P(id='RMA', style={'textAlign': 'center'})
                    ], width=4, className='mb-4'),
                
            ])
        ])
    ])
], fluid=True)

# Backend callback
@app.callback(
    [
        Output("FMAG","figure"),
        Output("FMMG", "figure"),
        Output("FMMAG", "figure"),
        Output("RAG", "figure"),
        Output("RMG", "figure"),
        Output("RMAG", "figure")
    ],
    [Input("SD", "value"),
     Input("SchoolType", "value")]
)
def update_cards(selected_district, selected_school_type):
    # Filter DataFrame based on selected district
    if selected_district == 'All':
        filtered_df = Data_df
    else:
        filtered_df = Data_df[Data_df['DISTNAME'] == selected_district]

    # Further filter by school type
    if selected_school_type != 'All':
        filtered_df = filtered_df[filtered_df['GRDTYPE'] == selected_school_type]
Selected columns= Data_df['Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, African American, STAAR Reading/ELA Rate',
    'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, All Students, STAAR Reading/ELA Rate',
    'CDI03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, American Indian, STAAR Reading/ELA Rate',
    'CD303ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Asian, STAAR Reading/ELA Rate',
    'CDR03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, At Risk, STAAR Reading/ELA Rate',
    'CDL03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, EL, STAAR Reading/ELA Rate',
    'CDE03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Econ Disadv, STAAR Reading/ELA Rate',
    'CDF03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Female, STAAR Reading/ELA Rate',
    'CDH03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Hispanic, STAAR Reading/ELA Rate',
    'CDM03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Male, STAAR Reading/ELA Rate',
    'CD403ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Pacific Islander, STAAR Reading/ELA Rate',
    'CDS03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Special Ed, STAAR Reading/ELA Rate',
    'CD203ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, Two or More Races, STAAR Reading/ELA Rate',
    'CDW03ARE1S18R': 'Campus 2018 Domain 1A: Approaches Grade Level STD, Grade 3, White, STAAR Reading/ELA Rate']
  # Calculate the average for each specified column
averages = {name: Data_df[col].mean() for name, col in column_names.items() if col in Data_df.columns}

    
    # Calculate the average for each specified column
averages = {name: Data_df[col].mean() for name, col in column_names.items() if col in Data_df.columns}

# Create a bar graph function
def create_bar_graph(averages):
    # Create the bar graph using Plotly Express
    fig = px.bar(
        x=list(averages.keys()),
        y=list(averages.values()),
        labels={'x': 'Category', 'y': 'Average Rate'},
        title='Average STAAR Reading/ELA Rate by Category'
    )

    # Generate pie charts
    pie_math = create_pie_chart(Ma, total_possible_points)
    pie_rla = create_pie_chart(Rla, total_possible_points)
    pie_science = create_pie_chart(sc, total_possible_points)
    pie_ss = create_pie_chart(ss, total_possible_points)
    pie_cg = create_pie_chart(cad, total_possible_points)
    pie_cg2 = create_pie_chart(pro, total_possible_points)
    
    return (pie_math, pie_rla, pie_science, pie_ss, pie_cg, pie_cg2)


# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8060)

SyntaxError: '[' was never closed (787718325.py, line 7)